### ISSUE TITLE
SWiFT Tv and Ts not equal

### ISSUE THREAD

**Issue by DriesAllaerts** [a2e-mmc/assessment#20]
@ewquon Conclusion from the notebook `assessment/datasets/SWiFT/TTU_tower_heatflux_stability.ipynb`  are incorrect. The ratio of Ts and Tv is calculated based on the theoretical relation and not the actual computed values, which gives a different result.

**Comment by jsauer-NCAR** [comment]
Can we point out the particular line or lines that leads to the problem....
e.g. 
"df['Tv/Ts'] = (1 + 0.61*q) / (1+0.51*q)
fig,ax = plot_timehistory_at_height(df.reset_index(1), 'Tv/Ts', heights) " 

and a suggested fix...
"df['Tv/Ts'] = df['Tv']/df['Ts']
fig,ax = plot_timehistory_at_height(df.reset_index(1), 'Tv/Ts', heights) "

which yields the following...
<img width="495" alt="Screen Shot 2019-10-08 at 2 25 34 PM" src="https://user-images.githubusercontent.com/22982605/66430640-c0005b00-e9d7-11e9-88d9-f52d30949603.png">

As we can see in the figure I've attached here, the ratio tends to be less than 1 (so high-bias in Tsonic) of 0.5%-2.0%, which might correspond to 1-6 K.

Is this what you (@DriesAllaerts) mean by "conclusions from the notebook...are incorrect"?  Just wanted to make sure we document precisely what you see as incorrect before you leave, so that we can address this issue in the future.

**Comment by ewquon** [comment]
Yes that's exactly correct, @jsauer-NCAR. I had asked @DriesAllaerts to submit a brief description of the issue more as a reminder to me to revisit this data analysis. I'd like to check the reference from which I got those equations, and also add a note about their validity.

**Comment by jsauer-NCAR** [comment]
Fair enough, thanks for the clarification, and making sure this didn't fall off of the radar.

**Comment by ewquon** [comment]
This was resolved by #25
